### ISSUE TITLE
[autodevops] stop environments

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/gitlab-ci-yml#114]
Petit souci dans la conf des jobs lorsqu'on clic sur "destroy environment" dans gitlab

`k8s-ns-killer` n'est pas détecté ni le job de destroy de la db azure

<img width="436" alt="Capture d’écran 2020-03-24 à 00 31 38" src="https://user-images.githubusercontent.com/124937/77372867-0ae41400-6d67-11ea-8a27-1f33ca1872c1.png">

https://docs.gitlab.com/ee/ci/yaml/README.html#environmenton_stop

**Comment by douglasduteil** [comment]
C'est pas bon signe...
On est sure que les pipelines peuvent avoir plusieurs `on_stop` ?

**Comment by revolunet** [comment]
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/46919
