### ISSUE TITLE
bug(mattermost): missing env variable

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/gitlab-ci-yml#127]
\from @revolunet  https://github.com/SocialGouv/gitlab-ci-yml/pull/125#issuecomment-611486434

> sniff il y a un bug pour detecter l'environnement, visiblement il manque les infos relatives à l'environnement 
testé avec https://github.com/SocialGouv/gitlab-ci-yml/blob/revolunet-patch-1/base_notify_github_stage.yml sans succes :/

**Comment by douglasduteil** [comment]
Can you link a log trace @revolunet  ?

**Comment by revolunet** [comment]
job : https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/jobs/459282

result : 

<img width="361" alt="Capture d’écran 2020-04-09 à 13 48 56" src="https://user-images.githubusercontent.com/124937/78904050-4cb9cd80-7a7c-11ea-99c0-f6315a3830ab.png">

**Comment by douglasduteil** [comment]
@revolunet :thinking: 
It's a missing `environment: name` I think

**Comment by douglasduteil** [comment]
@revolunet j'ai commit dans ta branch ;)
https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/commit/9fb1b9adfe66e93d794859a2aa5de2b651655511

**Comment by revolunet** [comment]
au top merci

**Comment by revolunet** [comment]
this wont work on master branch, i setup another issue for that

**Comment by douglasduteil** [comment]
It works on branches ?

**Comment by douglasduteil** [comment]
@revolunet j'ai commit dans ta branch ;)
https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/commit/4c6cc5fb536cc94ff309f791f842cf07261b7d83

**Comment by revolunet** [comment]
it does thanksssss

**Comment by douglasduteil** [comment]
@revolunet j'ai commit dans ta branch ;)
https://gitlab.factory.social.gouv.fr/SocialGouv/covid/-/commit/485249659ebed4d2cbfe589ee6e6bcdf386f7a8f

**Comment by revolunet** [comment]
booo
