### ISSUE TITLE
feature branches on autodevops_simple_app

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/gitlab-ci-yml#23]
Il semblerait que l'environnement de feature-branch n'envoie pas son url sur la PR GitHub : 

 - example PR : https://github.com/SocialGouv/siret2idcc/pull/31
 - related Pipeline : https://gitlab.factory.social.gouv.fr/SocialGouv/siret2idcc/-/jobs/281769

<img width="566" alt="Capture d’écran 2019-12-23 à 10 21 19" src="https://user-images.githubusercontent.com/124937/71348943-fe84cb00-256d-11ea-8278-9782c67ebcac.png">

**Comment by douglasduteil** [comment]
Closed with #26 , f6ef6519ac2ce907bcad4de1426e9ec0ab336861 , and 49b99d5a3b87856672395762b05f6ea623a0d5cb
