### ISSUE TITLE
feat(azure_db): migrate to helm-chart v7.0.0

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/gitlab-ci-yml#294]
\see https://github.com/SocialGouv/helm-charts/pull/78

- [ ] should launch job separately
- [ ] should log the job activity in the runner
- [ ] should bloc the runner while the job is still running
- [ ] should use secret from the local code (sealed maybe)

**Comment by revolunet** [comment]
deprecated with kosko-charts
