### ISSUE TITLE
recommanded way to implement in monorepo with multiple interdeps packages

### ISSUE THREAD

**Issue by devthejo** [SocialGouv/gitlab-ci-yml#427]
@douglasduteil @revolunet  je suis en train d''essayer de mettre à jour mon pipeline sur emjpm (il était resté à la version 8 de gitlab-ci-yml), et en partant d'autodevops je dois changer pas mal de choses petit à petit à cause d'une problématique spécifique: c'est un monorepo avec plusieurs packages, pour ce qui est de build des images dockers, c'est assez propre à implémenter, mais concernant les build js, test etc..., j'ai des interdépendences entre mes packages (app dépends de core et ui, api dépends de core), et certains tests dépendent donc du build de ces dépendences pour pouvoir tourner, ce qui ne correspond pas avec les stages prévus, je me demandais si il y avait une manière recommandée de gérer ce problème, soit au niveau de l'implémentation du pipeline, soit en changeant la gestion des packages (peut-être même en remplaçant lerna pas des symlinks dans node_module, ou un autre truc inventif). J'étais partis pour creuser tout seul, mais je me suis dis que tu pourrais peut-être me dire si tu as déjà eu ce cas de figure.

**Comment by devthejo** [comment]
@tglatt @douglasduteil une façon de procéder serait d'importer uniquement les sources depuis les paquets dépendants il suffit de remplacer et `main` dans dans le `package.json` pour le pointer sur `src` plutôt que sur la `dist`, gros avantage, un debug plus cohérent (car je sais pas ce qui cloche avec l'impémentation des sources maps, mais dès qu'un problème viens d'une dépendence compilée, c'est l'enfer pour retracer l'erreur), le hic c'est qu'il faut obligatoirement harmoniser la syntaxe js au sein du monorepo (ceci dit ça me semble une bonne chose) en faisant au moins en sorte que les dépots dépendants comprennent et soient capable de compiler la syntaxe de leurs dépendences (ce qui n'est pas le cas actuellement, mais ne saurait tarder car je m'y met dès maintenant !!!).

**Comment by douglasduteil** [comment]
@devthejo ce repo a pour focus de simplifier les pipelines des repos "simple" (pas les monorepo).
Il est possible d'utiliser des snippets dans un monorepo mais nous n'avons pas de reco unifié pour le moment...
https://github.com/SocialGouv/cdtn-admin/blob/master/.gitlab-ci.yml est exemple d'utilisation

L'update dans laquelle tu te lance va surement prendre un certain temps qui ne sera pas forcement au bénefice de la startup ⚠️ 
Il est préférable que tu binômes avec un membre de l'équipe SRE pour t'assurer que ton scope de travail ne va pas compter 3 semaines de refacto ^^

**Comment by devthejo** [comment]
@douglasduteil merci pour ton retour.
Cela dit je m'étais déjà lancé, et avec beaucoup d'élan 😆, @revolunet m'a informé qu'il était en vacances jusqu'au 28 et sinon tu es le seul que je connaisse de la SRE, et en plus tu es partout dans les commits sur les repo des outils de la fabrique donc je me suis dit que la question t'intéresserai. Bien que mon approche permettrais une intégration autodevops, j'ai finalement opté pour une solution plus simple (pour le pipeline, en ce qui concerne le reste, j'ai tout refactoré) en ne m'appuyant plus sur gitlab-ci-yml (plus simple à retracer le code et pas besoin de remonter le temps), cela m'a permis d'y implémenter helm 3 et de baser les déploiements sur helm template. Si au bout d'une demi-journée je m'étais rendu compte que cela allait me prendre 3 semaines, j'aurais effectivement fait autrement. Ceci dit, comme c'est les fêtes, que je débarque sur le projet etc... si il y a bien un moment où je peux me lâcher un peu à faire tout ce qui est dette technique j'ai l'impression que c'est maintenant, car j'imagine bien qu'après je devrais mettre ça de côté assez souvent. En plus tout ce qui est refacto me permet de bien appréhender la structure du projet, c'est important pour moi si je veux pouvoir travailler dessus efficacement à l'avenir.
